// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqqHdMyx8SYE94jzdqtON-aehW01116eU',
    appId: '1:42325381046:web:8ab4bce6ffc41c111abb17',
    messagingSenderId: '42325381046',
    projectId: 'goodplace-habbit-tracker',
    authDomain: 'goodplace-habbit-tracker.firebaseapp.com',
    storageBucket: 'goodplace-habbit-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-mSKV4BAZVm-y3kMG0342ChRvEHqnX8',
    appId: '1:42325381046:android:bf57bc64d453b85d1abb17',
    messagingSenderId: '42325381046',
    projectId: 'goodplace-habbit-tracker',
    storageBucket: 'goodplace-habbit-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_xnbui2RhmUmVUCDHdoNJfhtWUcZCzhw',
    appId: '1:42325381046:ios:2abd5e5bdd5f96081abb17',
    messagingSenderId: '42325381046',
    projectId: 'goodplace-habbit-tracker',
    storageBucket: 'goodplace-habbit-tracker.appspot.com',
    iosBundleId: 'com.miluni.goodplaceHabbitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_xnbui2RhmUmVUCDHdoNJfhtWUcZCzhw',
    appId: '1:42325381046:ios:2abd5e5bdd5f96081abb17',
    messagingSenderId: '42325381046',
    projectId: 'goodplace-habbit-tracker',
    storageBucket: 'goodplace-habbit-tracker.appspot.com',
    iosBundleId: 'com.miluni.goodplaceHabbitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqqHdMyx8SYE94jzdqtON-aehW01116eU',
    appId: '1:42325381046:web:425141ce256484b81abb17',
    messagingSenderId: '42325381046',
    projectId: 'goodplace-habbit-tracker',
    authDomain: 'goodplace-habbit-tracker.firebaseapp.com',
    storageBucket: 'goodplace-habbit-tracker.appspot.com',
  );
}
